---

- name: EPEL Packages are installed
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: RabbitMQ Packages are installed
  yum:
    name: rabbitmq-server
   
- name: RabbitMQ Service is started/enabled
  systemd:
    name: rabbitmq-server
    enabled: true
    state: started
